POST http://localhost:8001/users HTTP/1.1
Content-Type: application/json

{
  "payload": {
    "username": "jane",
    "email": "jane@ex.com",
    "password": "123"
  }
}

###

POST http://localhost:8001/social/tweets HTTP/1.1
Content-Type: application/json

{
  "owner_id": 1,
  "content": "Hello, world!"
}

###

POST http://localhost:8001/social/tweets/retweet HTTP/1.1
Content-Type: application/json

{
  "owner_id": 1,
  "tweet_id": 1,
  "content": "Retweet!"
}
